### ISSUE TITLE
执行lambdafm_predict抛出异常

### ISSUE THREAD

**Issue by supersush** [CastellanZhang/lambdaFM#8]
hi,CastellanZhang:
用lambdafm_train函数训练出模型之后，执行lambdafm_predict调用模型进行预测时抛出异常：
terminate called after throwing an instance of 'std::out_of_range'
  what():  stod
已放弃(吐核)

请问这个问题如何解决?谢谢！

**Comment by CastellanZhang** [comment]
把你训练和预测使用的参数贴一下，怀疑是参数设置有问题。

**Comment by supersush** [comment]
问题找到了，训练生成的模型文件里出现了3.70407e-310这种参数，predict的时候这种参数用stod方法转double的时候溢出了
